config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  get 'car_list', to: 'static_pages#car_list'
  resources :cars, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def new
    @car= Car.new
  end
  def create
    @car = Car.create(car_params)
    redirect_to root_path
  end

  private
  def car_params
    params.require(:car).permit(:car_make,:car_model,:car_year)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  def car_list
    @cars = Car.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cars/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add your favorite car</h1>
  <%= simple_form_for @car, url: cars_path do |f| %>
    <%= f.input :car_make %>
    <%= f.input :car_model %>
    <%= f.input :car_year %>
    <br />
    <%= f.submit "Add Car", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>*

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daniel's First Quiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/car_list.html.erb
<div class="booyah-box col-10 offset-1">
  <%= link_to 'Home', root_path, class: 'btn btn-primary btn-large float-left' %>
  <h1 class="text-center">Our Favorite Cars</h1>
  <br />
  <div class="text-center">
    <% @cars.each do |car| %>
      <%= car.car_year %> <%= car.car_make %> <%= car.car_model %>
      <br />
    <% end %>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Welcome to My Rails Application</h1>
  <br />
  <div class="text-center">
    <p>This application is brought to you by Daniel Ayala.</p>

    <p>This will be an application that is all about favorite cars. Add your favorite car to our list!</p>

    <%= image_tag image_url('audi1.jpg'), class: "img-fluid" %>

    <br class="clear" />
    <%= link_to 'Our favorite cars...', car_list_path, class: 'btn btn-primary btn-large float-left' %>
    <%= link_to 'Add a car...', new_car_path, class: 'btn btn-primary btn-large float-right' %>
    <br class="clear" />
  </div>
</div>